export const GET_ITEMS = 'GET_ITEMS'
export const FILTER_ITEMS = 'FILTER_ITEMS'
export const OPEN_CART = 'OPEN_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const EMPTY_CART = 'EMPTY_CART'